backend:
  name: github
  repo: noah004B/my-gridsome-site

media_folder: "assets/static"
public_folder: "/assets/static"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

